source 'https://github.com/CocoaPods/Specs.git'

react_native_path = '../node_modules/react-native'
terminus_path = '../node_modules/@terminus'
platform :ios, '9.0'
inhibit_all_warnings!

target 'social' do

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'

  # Third party deps
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'

  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  pod 'trnw-toast', :path => terminus_path +'/trnw-toast/ios'
  pod 'react-native-cookies', :path => terminus_path +'/react-native-cookies/ios'
  pod 'RNSVG', :path => '../node_modules/react-native-svg/RNSVG.podspec'
  pod 'react-native-image-picker', :path => terminus_path +'/react-native-image-picker/ios'
  pod 'react-native-camera', :path => terminus_path +'/react-native-camera/ios'
  pod 'IQKeyboardManager'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  
  pod 'rn-debug', :path => '../node_modules/@terminus/rn-debug/ios', :configurations => ['Debug','Test']
  pod 'rn-env', :path => '../node_modules/@terminus/rn-debug/ios'
  pod 'react-native-social', :path => '../../ios/react-native-social.podspec'

  pod 'React', :path => '../node_modules/react-native/', :subspecs => [
        'Core',
        'CxxBridge',
        'RCTNetwork',
        'RCTWebSocket',
        'RCTGeolocation',
        'RCTImage',
        'RCTAnimation',
        'RCTActionSheet',
        'RCTSettings',
        'RCTLinkingIOS',
        'RCTText',
        'DevSupport'
    ]
end

project 'social', 'Test' => :release, 'Debug' => :debug,'Release' => :release

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'yoga'
          # Workaround: react-native v0.52 bug issue #17274
          # node_modules/react-native/ReactCommon/yoga/yoga/YGNodePrint.cpp:208:46: Implicit conversion loses integer
          # precision: 'size_type' (aka 'unsigned long') to 'const uint32_t' (aka 'const unsigned int')
          # https://github.com/facebook/react-native/issues/17274#issuecomment-356363557
          target.build_configurations.each do |config|
              config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
              config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
          end
      end
      if target.name == "RNSVG"
          target.build_configurations.each do |config|
              config.build_settings['GCC_NO_COMMON_BLOCKS'] = 'NO'
          end
      end
      if (target.name == 'react-native-env-switch')
        target.build_configurations.each do |config|
            if config.name == 'Release'
                puts "#{target.name} config build_settings['GCC_PREPROCESSOR_DEFINITIONS']<<RELEASE=1 "
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RELEASE=1'
            end
        end
    end
  end
end
